CREATE TABLE [dbo].[Post]
(
	IDPost INT PRIMARY KEY IDENTITY,
	DetallePost NVARCHAR(MAX) NOT NULL,
	FechaRegistro DATETIME DEFAULT GETDATE(),
	UsuarioId INT NOT NULL,
	Tipo NVARCHAR(100) --AGREGAR TABLA
)
